# Generated by Django 5.1.3 on 2024-11-19 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centralbookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('Organizer_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Organizer_Name', models.CharField(max_length=100)),
                ('Organizer_Address', models.CharField(max_length=255)),
                ('Organizer_Type', models.CharField(choices=[('Internal', 'Internal'), ('External', 'External')], default='Internal', max_length=8)),
            ],
        ),
    ]
