# Generated by Django 5.1.3 on 2024-11-19 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centralbookings', '0004_external'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contact_Name', models.CharField(max_length=100)),
                ('Contact_Email', models.EmailField(max_length=100)),
                ('Contact_Number', models.CharField(max_length=12)),
                ('Organizer_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centralbookings.organizer')),
            ],
        ),
    ]
