# Generated by Django 5.1.3 on 2024-11-19 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centralbookings', '0005_contactperson'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('ID_Number', models.AutoField(primary_key=True, serialize=False)),
                ('Participant_Name', models.CharField(max_length=100)),
                ('Birth_Date', models.DateField()),
                ('Department', models.CharField(max_length=100)),
                ('Participant_Type', models.CharField(choices=[('Student', 'Student'), ('Faculty', 'Faculty'), ('Staff', 'Staff')], default='Student', max_length=8)),
            ],
        ),
    ]
