# Generated by Django 5.1.3 on 2024-11-28 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centralbookings', '0011_organizer_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('Activity_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Activity_Name', models.CharField(max_length=100)),
                ('Activity_Location', models.CharField(max_length=255)),
                ('Activity_Date', models.DateField()),
                ('Start_Time', models.TimeField()),
                ('End_Time', models.TimeField()),
                ('Organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='centralbookings.organizer')),
            ],
        ),
    ]
