# Generated by Django 5.1.3 on 2024-12-02 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centralbookings', '0014_userparticipant'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='Organizer_Number',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
    ]
