# Generated by Django 5.1.3 on 2024-12-02 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centralbookings', '0015_organizer_organizer_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityList',
            fields=[
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='centralbookings.activity')),
                ('expected_participants', models.IntegerField(default=0)),
            ],
        ),
    ]
