# Generated by Django 5.1.3 on 2024-12-02 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centralbookings', '0016_activitylist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='centralbookings.activity')),
                ('attended', models.BooleanField(default=False)),
            ],
        ),
    ]
