# Generated by Django 5.1.3 on 2024-12-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centralbookings', '0017_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='Participant_Number',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
