# Generated by Django 5.1.3 on 2024-12-02 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centralbookings', '0018_participant_participant_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centralbookings.participant')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centralbookings.schedule')),
            ],
        ),
    ]
